packages:
  - "./packages/noka-tsconfig/"
  - "./packages/eslint-config-noka/"
  - "./packages/noka-utility/"
  - "./packages/noka/"
  - "./packages/noka-cli/"
  - "./packages/noka-orm/"
  - "./packages/noka-app/"
  - "./packages/noka-app-spa/"