packages:
  - "./packages/noka-tsconfig/"
  - "./packages/eslint-config-noka/"
  - "./packages/noka-util/"
  - "./packages/noka/"
  - "./packages/noka-cli/"
  - "./packages/noka-orm/"
  - "./packages/noka-tpl-site/"
  - "./packages/noka-tpl-app/"