# =============================================================================
# 基础配置
# 应用默认将自动选取一个可用端口，可在此指定监听端口
# 同时可指定应用绑定的 hostname，域名或 IP
# 此外，也可在 Application 实例化时，通过 options 指定端口
# -----------------------------------------------------------------------------

port: 8080
hostname: 0.0.0.0

# 如果启用 HTTPS 可在此配置相应的证书
# secure: 
#   key: path/to/key
#   cert: path/to/cert

# =============================================================================
# 配置 Loader 第一步：
# 在此声明要在当前应用启用的 loader，格式为 `<CONF_NAME>: <包名或路径>`
# -----------------------------------------------------------------------------

loader_imports:
  # loader_conf_name: loader_package


# =============================================================================
# 配置 Loader 第二步：
# 在此配置已经启用的 loader
# 如有需要，内建 loaders 也可直接在此配置或禁用，格式为 `<CONF_NAME>: false`     
# -----------------------------------------------------------------------------

loader_options:
  # loader_conf_name: 
  #   option_a: ...
  #   option_b: ...
  # loader_config_name: false


# =============================================================================
# 自定义配置
# 除了「基础配置」和「Loader 配置」，可在此添加自定义配置
# 可在 controller/service/model 中，通过 `@config(<path>)` 注入配置内容
# 另外，配置的整体内容，可通过全局应用实例获取（示例代码：`app.config`）
# -----------------------------------------------------------------------------

# custom_conf_name: 
#   option_a: ...
#   option_b: ...
