# -----------------------------------------------------------------------------
# 基础配置
# 应用默认将自动选取一个可用端口，可在此指定监听端口
# 此外，也可在 Application 实例化时，通过 options 指定端口
# -----------------------------------------------------------------------------

# prot: 8080


# -----------------------------------------------------------------------------
# 配置 Loader 第一步：
# 在此声明要在当前应用启用的 loader，格式为 `<CONF_NAME>: <包括名路径>`
# 如果有需要，也可在此禁用内建 loader，格式为 `<CONF_NAME>: false`
# -----------------------------------------------------------------------------

loaders:
  # loader_conf_name: loader_package


# -----------------------------------------------------------------------------
# 配置 Loader 第二步：
# 在此配置已经启用的 loader
# 如有需要，内建 loaders 也可直接在此配置或禁用，格式为 `<CONF_NAME>: false`     
# -----------------------------------------------------------------------------

# loader_conf_name: 
#   option_a: ...
#   option_b: ...


# -----------------------------------------------------------------------------
# 自定义配置
# 除了「基础配置」和「Loader 配置」，可在此添加自定义配置
# 可在 controller/service/model 中，通过 `@config(<path>)` 注入配置内容
# 另外，配置的整体内容，可通过全局应用实例获取（示例代码：`app.config`）
# -----------------------------------------------------------------------------

# custom_conf_name: 
#   option_a: ...
#   option_b: ...